-- 1. Create Doctors Table
CREATE TABLE IF NOT EXISTS doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname TEXT NOT NULL,
    lastname TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    designation TEXT NOT NULL,
    password TEXT NOT NULL,
    timestamp BIGINT,
    timezone TEXT
);

-- 2. Create Patients Table
CREATE TABLE IF NOT EXISTS patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    dob TEXT NOT NULL,
    password TEXT NOT NULL,
    nextappointment TEXT,
    age INTEGER,
    condition TEXT,
    status TEXT,
    timestamp BIGINT,
    notes TEXT
);

-- 3. Create Patient History Table
CREATE TABLE IF NOT EXISTS patienthistory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patientusername TEXT NOT NULL REFERENCES patients(username),
    date TEXT NOT NULL,
    event TEXT NOT NULL,
    details TEXT
);

-- Enable Row Level Security (RLS) is recommended in Supabase, but for now, 
-- ensure you have an 'anon' policy or disable RLS for testing.
ALTER TABLE doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE patienthistory ENABLE ROW LEVEL SECURITY;

-- Simple "Allow All" policies for testing (Replace with restricted policies for production)
create policy "Allow all for anon" on doctors for all using (true) with check (true);
create policy "Allow all for anon" on patients for all using (true) with check (true);
create policy "Allow all for anon" on patienthistory for all using (true) with check (true);
